### ISSUE TITLE
Rendering Amp.Sidebar to body tag

### ISSUE THREAD

**Issue by antonybritto** [dfrankland/react-amphtml#11]
Currently in my react SSR application, i tried using AMP.sidebar which renders the Sidebar inside the react root component ("div" tag) rather than rendering as direct child of body Tag. Anyway work around to fix this?

**Comment by dfrankland** [comment]
`react-amphtml` isn't using any specific logic in regards to sidebars. Are you talking about the overlay or the sidebar itself?

The AMP docs mention that the `<amp-sidebar />` should be used withing `<body />`:
https://www.ampproject.org/docs/reference/components/amp-sidebar#behavior

Seems like the overlay is hardcoded to render in the `<body />` tag too:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-sidebar/0.1/amp-sidebar.js#L310

**Comment by dfrankland** [comment]
Feel free to re-open if this is still an issue 👍

**Comment by ghashi** [comment]
According to the [doc](https://www.ampproject.org/docs/reference/components/amp-sidebar) 

> <li>The <code>&lt;amp-sidebar&gt;</code> should be a direct child of the <code>&lt;body&gt;</code>.</li>

So, the issue here is that at runtime you'll see the following message if you [don't render your react app in document.body](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375#486f):

> The parent tag of tag 'amp-sidebar' is 'div', but it can only be 'body'. (see https://www.ampproject.org/docs/reference/components/amp-sidebar)

**Comment by ghashi** [comment]
related (there's a possible workaround): https://stackoverflow.com/questions/39857415/amp-sidebar-does-it-absolutely-have-to-be-the-child-of-the-body-why
