### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by peltomaa** [dfrankland/react-amphtml#14]
I'm using this great library in couple of my projects which are using typescript. Now I'm bypassing ts errors with // @ts-ignore flag but it would be great to typings in this project.

**Comment by dfrankland** [comment]
I've never used TypeScript before, but if you help me a bit I am sure I could do that 👍

**Comment by dfrankland** [comment]
@peltomaa thank you for the PR! I've published your partial types in `react-amphtml@3.0.1`.
