### ISSUE TITLE
Is there amp-access support?

### ISSUE THREAD

**Issue by alankent** [dfrankland/react-amphtml#19]
Hi. I came across this project and was giving it a go. Is there amp-access support? To get this going you need to have a `<script>`  tag in `<head>` holding the authentication information (JSON). You then also have to add `amp-access` and `amp-access-hide` attributes to elements around the place to hide/show them based on current access rights.

Thanks!

**Comment by dfrankland** [comment]
I don't know, but I'll do some digging to see if it's available or if I can create a utility to make it work 👍

**Comment by alankent** [comment]
Thanks! I am `@akent99` on twitter if you want to follow me back to chat.  (I am exploring server side AMP rendering using React + Next to see if a useful tool or not.)
