### ISSUE TITLE
Error: "sidebar" is not a valid amphtml directive.

### ISSUE THREAD

**Issue by imparvez** [dfrankland/react-amphtml#2]
Hey, @dfrankland, while I was using react-amphtml plugin to create and use AMP's component inside my react set-up, I got stuck with amp-sidebar.
`AmpSideBar = amphtml('sidebar', addScript)`

`Error: "sidebar" is not a valid amphtml directive.
     at reactAmpHtml (/Users/parvezshaikh/Sites/WEB/site/node_modules/react-amphtml/index.js:27:11)`

Can you please guide me through this?

**Comment by dfrankland** [comment]
I've recently updated this module. Check the tests here for examples of how to use `react-amphtml`:
https://github.com/dfrankland/react-amphtml/blob/master/src/__tests__/react-amphtml.spec.js
