### ISSUE TITLE
What's specName and why is it necessary?

### ISSUE THREAD

**Issue by ghashi** [dfrankland/react-amphtml#21]
I've checked [react-amphtml.spec.js](https://github.com/dfrankland/react-amphtml/blob/7221879f49f289855a2574557afbead811c532a8/src/__tests__/react-amphtml.spec.js) and noticed that the `AmpImg` has a prop called `specName`.

``` html
        <div>
          <Amp.AmpImg specName="default" src="test" />
          <Amp.AmpPixel src="blah" />
        </div>
```

I've tried using this component (`Amp.AmpImg`) without setting this prop (`specName`) but it won't render a `<amp-img>` at runtime, so this props is mandatory.

Why is it necessary?

**Comment by dfrankland** [comment]
Each AMP element can be used in different ways depending where and how it is used. To separate the use-cases and props for each of these for individual AMP elements that require it, we add a `specName` prop. For your example use of `AmpImg`, check the validator rules that dictate the props dependent on spec name here:
<https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L4047-L4096>

**Comment by ghashi** [comment]
Is it a bad idea to set `specName="default"` as a default value if we don't set it? 
Another idea is to throw an error on the console when something is missing.

**Comment by dfrankland** [comment]
Sometimes components do not have a `default` `specName` which is why we cannot set it as a property of `defaultProps`. There should be a warning thrown by `PropTypes` is the `specName` property is not given: https://github.com/dfrankland/react-amphtml/blob/f5e940b0bf06f99a5922c95f3ea61eae39929a7b/src/amphtml/codegen/duplicateWrapperComponentCode.js#L29

**Comment by ghashi** [comment]
Ok, I understand now! Thanks.

Can I close this issue (or could you do it for me?)?
