### ISSUE TITLE
index.d.ts: ampScripts property of AmpScriptsManagerProps should be AmpScripts and not AmpScripts[]

### ISSUE THREAD

**Issue by eryi** [dfrankland/react-amphtml#22]
Looking at
https://github.com/dfrankland/react-amphtml/blob/master/src/setup/AmpScriptsManager.js#L22

It seems like `ampScripts` property of `AmpScriptsManagerProps` should be `AmpScripts` and not `AmpScripts[]`
https://github.com/dfrankland/react-amphtml/blob/master/index.d.ts#L42

**Comment by dfrankland** [comment]
Is there a way to write tests for this? Also, please feel free to make a PR.

**Comment by eryi** [comment]
Currently, the only way to test types is to write some sample code in TypeScript and try compiling it using `tsc index-test.ts`. That's what they are doing at DefinitelyTyped.

I apologize for the 'drive by' issue. However, I'm not using TypeScript and this library together in any of my projects so I'm not the best person to ensure that the types are correct. Please feel free to close this issue or wait for a more qualified person to come along.
