### ISSUE TITLE
How to pass props without value to component?

### ISSUE THREAD

**Issue by ghashi** [dfrankland/react-amphtml#23]
# the problem
amp-accordion has an [`animate`](https://www.ampproject.org/docs/reference/components/amp-accordion#animate) prop that I would like too add, but I don't find how to do it.

# what I've tried

1) set it as specified in the [docs](https://ampbyexample.com/components/amp-accordion/#animated-accordions)
``` jsx
<Amp.AmpAccordion animate>
``` 
renders
``` jsx
<amp-accordion animate="true" class="i-amphtml-element i-amphtml-layout-container i-amphtml-layout">
```
which is not a valid amp-html

2) Set [animate={null}](https://stackoverflow.com/questions/37828543/how-to-pass-props-without-value-to-component) 
``` jsx
<Amp.AmpAccordion animate={null}>
```
renders
``` jsx
<amp-accordion class="i-amphtml-element i-amphtml-layout-container i-amphtml-layout">
```

**Comment by dfrankland** [comment]
Hello!

This is more related to the W3C DOM specification and React in general. Any attribute with an empty string will render into the DOM without a value.

---

W3C relevant documentation: https://www.w3.org/TR/html5/syntax.html#elements-attributes

> **Empty attribute syntax**
> Just the attribute name. The value is implicitly the empty string.
>
> > In the following example, the disabled attribute is given with the empty attribute syntax:
> > ```html
> > <input disabled>
> > ```
>
> If an attribute using the empty attribute syntax is to be followed by another attribute, then there must be a space character separating the two.

---

Example JSX:

```js
<Amp.AmpAccordion animate="">
```

...renders to...

```html
<amp-accordion animate class="i-amphtml-element i-amphtml-layout-container i-amphtml-layout">
```
