### ISSUE TITLE
Amp.AmpState not rendering

### ISSUE THREAD

**Issue by tannerbaum** [dfrankland/react-amphtml#24]
Hi there, I hope I am just missing something but I attempted to use your Amp.AmpState helper and found that it wasn't rendering anything in my final HTML. As far as I can tell, I am writing the code as described in the documentation.

```js
import * as React from 'react';
import styled from "styled-components";
import * as Amp from 'react-amphtml';
import * as AmpHelpers from 'react-amphtml/helpers';

// ...

export default (props: Props) => {

       // ... 

	return (
		<AudioWrapper> //Styled component inside a larger Amp document 
			<Amp.AmpState id="myState">
			{{
				"content": 'collapsed',
			}}
			</Amp.AmpState>
		<div className="audio-player">
                // ... 

```

This may be due to your issue facebook/react#12568 as I am using React's renderToString, but I will note that AmpHelpers.Bind is outputting correctly (even if Storybook is stripping it out for some reason: storybooks/storybook#3776).

For now I am going to try to use the target selector to achieve the functionality I need, but this may not be good enough down the road.

**Comment by BosenY** [comment]
the same problem with you

**Comment by dfrankland** [comment]
Should work starting with version 3.1.0
