### ISSUE TITLE
How to use `amp-lightbox-gallery` with Carousel?

### ISSUE THREAD

**Issue by ghashi** [dfrankland/react-amphtml#25]
I would like to use `amp-lightbox-gallery` with carousel. What's the right way to do it?

Nowadays I'm doing this:
``` jsx
<Amp.AmpCarousel width='1' height={aspectRatio} layout='responsive' type='slides' lightbox=''>
  {imageComponentList}
</Amp.AmpCarousel>
```

But the script for `amp-lightbox-gallery` isn't automatically imported:
``` js
<script async custom-element="amp-lightbox-gallery" src="https://cdn.ampproject.org/v0/amp-lightbox-gallery-0.1.js"></script>
```

**Comment by dfrankland** [comment]
This should be fixed since a long while ago. If you are still having an issue, feel free to reopen.
