### ISSUE TITLE
Amp-ad specName error with Server Side react with version 3.0.1

### ISSUE THREAD

**Issue by masakikomine** [dfrankland/react-amphtml#26]
Hi, we recently updated our react-amphtml version to 3.0.1 and were implementing Amp-ads in our server-side React application.

After adding the AmpAd component in page we are getting the following error.
Warning: Failed prop type: Invalid prop `specName` of value `amp-ad` supplied to `Script$$1`, expected one of ["amphtml engine v0.js script","amp4ads engine amp4ads-v0.js script",

Here is what the React JSX looks like
`      <AmpAd
        specName={'default'}
        id={`${adName}-${position}`}
        type="doubleclick"
        data-slot={sitename}
        json={JSON.stringify({ targeting })}
        width={adDimensions[0]}
        height={adDimensions[1]}
      />`

Changing the prop specName to spec-name resolves the error message but then introduces a new error at render time:
"Warning: Failed prop type: The prop `specName` is marked as required in `AmpAd`, but its value is `undefined`."

Is there a possible issue with the react amphtml specName with Amp-ads?  If not, is there a solution to this issue? Thank you.

**Comment by dfrankland** [comment]
Looking at the warning thrown, you can find both of the possible solutions you may use:

*   `amphtml engine v0.js script`
*   `amp4ads engine amp4ads-v0.js script`

Assuming that you are using the normal `ampthml` (not `amp4ads`), you should use the first one: `amphtml engine v0.js script`.

**Comment by masakikomine** [comment]
We were able to solve the issue with adding amp-ad to the addExtention call. Thank you!

`ampScripts.addExtension('amp-analytics', 'amp-ad');`

**Comment by yossisp** [comment]
I'm also having an error with `specName`, below is the console message:

> Warning: Failed prop type: The prop `specName` is marked as required in `AmpSidebar`, but
>  its value is undefined.
>     in `AmpSidebar`

> expected one of ["default","amp-story >> amp-sidebar"].
>     in AmpSidebar

As far as I understand `specName` refers to some kind of amp extension but I'm not sure this is the purpose of `specName` and what value should be supplied to it (`default` or `amp-story >> amp-sidebar`).

The element which triggers the message looks like this:

```
import * as Amp from 'react-amphtml';

const AmpSidebarComponent = () => (
  <AmpSidebar id="sidebar" layout="nodisplay" side="left">
  	{/* content */}
  </AmpSidebar>
);
```

I'm using the version 3.0.0.
