### ISSUE TITLE
React 16.4.2 and AmpHelpers.Action

### ISSUE THREAD

**Issue by harmony7** [dfrankland/react-amphtml#27]
ReactDOM 16.4.2 (released yesterday) made a [change that sanitizes unknown attribute names](https://github.com/facebook/react/pull/13302) and drops those attributes outright. So the workaround that `AmpHelpers.Action` uses does not work anymore.

Not sure how you'd work around this, just putting it out there.  I reverted to ReactDOM 16.4.1 for now.

**Comment by dfrankland** [comment]
Should work starting with version 3.1.0
