### ISSUE TITLE
amp-mustache

### ISSUE THREAD

**Issue by BosenY** [dfrankland/react-amphtml#28]
The extension 'amp-mustache' is referenced at version '0.1' which is a deprecated version. Please use a more recent version of this extension. This may become an error in the future.

**Comment by jlarmstrongiv** [comment]
I also see that browser warning.  A version bump would be great 👍

**Comment by alexandrefugita** [comment]
Hi there,

Any news about this? This update would be very appreciated.

Thanks

**Comment by dfrankland** [comment]
Should work starting with version 3.1.1
