### ISSUE TITLE
Warning: Invalid attribute name: `⚡`

### ISSUE THREAD

**Issue by nahushf** [dfrankland/react-amphtml#32]
On adding react-amphtml to a nextjs project, everything seems to run fine but the following warning keeps getting thrown:
`Warning: Invalid attribute name: `⚡`` .
What am I doing wrong?

I have reproduced the issue in the https://github.com/nahushf/next-amp-error repository.
react-amphtml has been configured in the _document.js file

Operating system:
Windows 10(Windows subsystem for linux)

Node JS version:
v8.12.0

**Comment by jlarmstrongiv** [comment]
This sounds similar to #29 The workaround there should fix it

**Comment by nahushf** [comment]
@jlarmstrongiv Yes, that fixed it. Closing.
