### ISSUE TITLE
Proper way to add analytics

### ISSUE THREAD

**Issue by freynolds** [dfrankland/react-amphtml#33]
Hi, first of all, excellent repo, I'm loving how everything works so well.

My issue is the following, in order to add segment I finally used a hack to add the script data. It works but clearly is not ideal.

This is my current code

```  
<AmpAnalytics
    type="segment"
    dangerouslySetInnerHTML={{__html: '<script type="application/json">{"vars":{ "writeKey": "abc", "name": "cde" }}</script>'}}
  >
  </AmpAnalytics>
```

Any clue on how to do this less _dangerously_

Thanks!

**Comment by dfrankland** [comment]
In this case, it's not really dangerous to do what you are doing. From the docs: https://reactjs.org/docs/dom-elements.html.

> In general, setting HTML from code is risky because it’s easy to inadvertently expose your users to a cross-site scripting (XSS) attack.

The content you are using `dangerouslySetInnerHTML` with is static and rendered only on the server-side, which mitigates any potential risk. We could improve this component to `dangerouslySetInnerHTML` for the user, but under the hood the component would do the same thing.

**Comment by freynolds** [comment]
Ok, thanks for the reply, I thought I was hacking my way to something that already was working in the repo but I couldn't find how to make it work, if this is a proper solution for this, then I'm glad I found it.
Best regards
