### ISSUE TITLE
Using AMpAnimation inside React

### ISSUE THREAD

**Issue by chandanbhandari** [dfrankland/react-amphtml#34]
I am trying to use AmpAnimation inside a component. I am getting an error Cannot call a class as a function
TypeError: Cannot call a class as a function
    at Object.classCallCheck (/node_modules/react-amphtml/dist/chunk1.js:14:11)
    at AmpScripts (/node_modules/react-amphtml/dist/setup.js:16:17)
    at processChild (/node_modules/react-dom/cjs/react-dom-server.node.development.js:2126:14) ....

find code below: 

```
<Amp.AmpAnimation id="hideAnim" layout="nodisplay">
    <AmpSetup.AmpScripts type="application/json" >
      {hideAnim}
    </AmpSetup.AmpScripts>
  </Amp.AmpAnimation >;

const hideAnim = {
  "fill": "both"
  "duration": "200ms",
  "iterations": "1",
  "direction": "alternate",
  "animations": [
    {
      "selector": "#download-button",
      "keyframes": [
        { "opacity": "0", "visibility": "hidden" }
      ]
    }
  ]
};
```

is there a proper way ro use animation?

**Comment by dfrankland** [comment]
Your problem is that you are trying to use `AmpSetup.AmpScripts` as a component, but it is not a React component. Re-open if you are still having an issue.
