### ISSUE TITLE
How do you recommend adding styling?

### ISSUE THREAD

**Issue by HoraceShmorace** [dfrankland/react-amphtml#35]
I'm trying to use `styled-components`, but of course the custom style tags aren't being added. Recommendations?

**Comment by dfrankland** [comment]
I like to use `styled-components` too! I have a nice of example of combining this library with `styled-component` here: https://github.com/dfrankland/ampreact/blob/master/pages/_document.js

**Comment by HoraceShmorace** [comment]
Awesome, thanks!
