### ISSUE TITLE
React 16 issues

### ISSUE THREAD

**Issue by svdoever** [dfrankland/react-amphtml#4]
I want to move to React 16, on installation I get the following issue:

npm WARN react-amphtml@2.0.0 requires a peer of react@^15.6.2 || ^16.0.0 but none was installed.
npm WARN react-amphtml@2.0.0 requires a peer of react-dom@^15.6.2 || ^16.0.0 but none was installed.

And the following errors:

These dependencies were not found:

* react-dom/lib/DOMProperty in ./node_modules/react-amphtml/dist/index.js
* react-dom/lib/ReactInjection in ./node_modules/react-amphtml/dist/index.jsThis functionality is only used in whitelist(), tried to copy the index.js file from the react-amphtml package, remove the imports and remove the whitelist function, but that did not help...

Any help would be appreciated...

**Comment by dfrankland** [comment]
React 16 doesn't ship with `react-dom/lib/ReactInjection` or `react-dom/lib/DOMProperty` which causes this issue. Instead of handling that within `react-amphtml`, I am planning to let the user worry about that. React 16 doesn't whitelist attributes which make this much easier to deal with.

**Comment by dfrankland** [comment]
Should be fixed with #5
