### ISSUE TITLE
Typed components missing common element attributes

### ISSUE THREAD

**Issue by parkjh** [dfrankland/react-amphtml#44]
Hello,

in the example below, there is a tslint error when implementing component, saying that width and height props does not exist on the component...
so when generating the amphtml types in codegen, are these props intentionaly missing or there is a better workaround?

```
<AmpYoutube
    data-videoid={content![1]}
    width="960"
    height="540"
    i-amphtml-layout="responsive"
/>
```

**Comment by dfrankland** [comment]
Oh! It's probably not intentional. I'll have to look into this.

**Comment by parkjh** [comment]
hello @dfrankland, 

I had a go at adding the common layout attributes to the codegen here https://github.com/dfrankland/react-amphtml/pull/46
and I was wondering what you thought of it?

**Comment by seacloud9** [comment]
@dfrankland and @parkjh I recently have been evaluating react-amphtml.  I have noticed a few things.  Responsive layout does not work.  Also when I follow the generation instructions I receive errors withing rollup about `Script`.

@parkjh I also see the same errors when I compile your branch.  Is there a branch available that will compile with responsive layout capabilities? Or am I simply missing a step.  Let me know thanks.

**Comment by carneiroDotDev** [comment]
Exactly the same as related by @parkjh but for amp-instagram: 
        <AmpInstagram
            data-shortcode={content.replace('https://www.instagram.com/p/', '')}
            data-captioned
            width=""
            height=""
        /> 

Width and height are not TS allowed props, however, these are required by the AMP validator. =/ Tried to simply put these props in AmpInstagramInterface but produced other strange errors. 

If somebody finds a workaround please let me know =)

**Comment by carneiroDotDev** [comment]
The same but with twitter.

**Comment by carneiroDotDev** [comment]
No more activity on this repo 😢 ?

**Comment by parkjh** [comment]
@luizdotpro it seems so, our team decided to just build the amp components ourselves instead...

So I am now closing this issue.

**Comment by dfrankland** [comment]
Y'all are welcome to make PRs! I am not focusing heavily on this project at the moment, so I can't make every fix myself.

**Comment by carneiroDotDev** [comment]
I would like to send a PR, but it seemed so abandoned that I gave up.
