### ISSUE TITLE
Amp.* components do not use same "className" behavior as other react components

### ISSUE THREAD

**Issue by blobcat** [dfrankland/react-amphtml#8]
When adding a css class attribute to an Amp.* tag, you must use `class="blah"` rather than `className="blah"`, as other standard react components do. Using "className" appears to renders as a `classname` attribute instead of `class`.

**Comment by dfrankland** [comment]
Yes, that's because `amp-*` components are Web Components which React does not do the `className` to `class` transform on.

https://reactjs.org/docs/web-components.html#using-web-components-in-react

I think for convenience we should add some that does this for all `Amp.*` components.

**Comment by dfrankland** [comment]
Should be fixed with `v2.2.1`!

https://github.com/dfrankland/react-amphtml/commit/bcb3f28c66d28a30a9bbcc293a8bab993222f9e3

**Comment by blobcat** [comment]
You are awesome, thank you!
